---
- name: Deploy Zabbix Agent 2 (multi-platform, dynamic repo URLs)
  hosts: all
  become: yes
  vars:
    zabbix_version: "7.4"
    zabbix_server: "192.168.1.20"   # <-- change to your Zabbix server IP/hostname
    zabbix_hostname: "{{ inventory_hostname }}"
    zabbix_agent_conf: "/etc/zabbix/zabbix_agent2.conf"

  tasks:
    # Debian family (Debian + Ubuntu)
    - name: Set Zabbix repo URL for Debian/Ubuntu
      set_fact:
        zabbix_repo_url: >-
          {% if ansible_distribution == "Debian" and ansible_distribution_major_version == "13" %}
          https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+debian13_all.deb
          {% elif ansible_distribution == "Debian" and ansible_distribution_major_version == "12" %}
          https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+debian12_all.deb
          {% elif ansible_distribution == "Ubuntu" %}
          https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+ubuntu{{ ansible_distribution_major_version }}.04_all.deb
          {% else %}
          ""
          {% endif %}
      when: ansible_os_family == "Debian"

    - name: Download Zabbix repo package (Debian/Ubuntu)
      get_url:
        url: "{{ zabbix_repo_url }}"
        dest: /tmp/zabbix-release.deb
        mode: '0644'
      when: ansible_os_family == "Debian" and zabbix_repo_url != ""

    - name: Install Zabbix repo package (Debian/Ubuntu)
      apt:
        deb: /tmp/zabbix-release.deb
        state: present
      when: ansible_os_family == "Debian" and zabbix_repo_url != ""

    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian" and zabbix_repo_url != ""

    # RHEL/CentOS repo setup
    - name: Install Zabbix repo on RHEL/CentOS
      yum:
        name: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-{{ zabbix_version }}-1.el{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_os_family == "RedHat"

    # Install agent
    - name: Install Zabbix Agent 2
      package:
        name: zabbix-agent2
        state: present

    # Deploy config
    - name: Deploy Zabbix Agent 2 configuration
      copy:
        dest: "{{ zabbix_agent_conf }}"
        content: |
          PidFile=/var/run/zabbix/zabbix_agent2.pid
          LogFile=/var/log/zabbix/zabbix_agent2.log
          LogFileSize=0
          Server={{ zabbix_server }}
          ServerActive={{ zabbix_server }}
          Hostname={{ zabbix_hostname }}
          Include=/etc/zabbix/zabbix_agent2.d/*.conf
      notify: Restart Zabbix Agent 2

    - name: Ensure Zabbix Agent 2 is enabled and running
      service:
        name: zabbix-agent2
        state: started
        enabled: yes

  handlers:
    - name: Restart Zabbix Agent 2
      service:
        name: zabbix-agent2
        state: restarted
